### ISSUE TITLE
No images found with the specified description.

### ISSUE THREAD

**Issue by agentediego** [mariosantella/wp_imgsed_feed#1]
Hello, I am getting this error

I already saved the name with @ at the beginning and also without the @ at the beginning.
I've already limited it to just showing 1 photo
I've done everything I can and still have the same error

**Comment by mariosantella** [comment]
Hey mate.. so sorry :( 
today imgsed became imginn and hardened protection from scraping.. 
just tried to work around with this with no luck.. really sorry but it needs time..
DM me if you find alternative solutions

ciao
